vim.g.mapleader = " "
vim.keymap.set("n", "<leader>fe", vim.cmd.Ex)
vim.keymap.set("n", "d", "\"_d")
vim.keymap.set("n", "D", "\"_D")
vim.keymap.set("v", "d", "\"_d")
vim.keymap.set("v", "D", "\"_D")
vim.keymap.set("n", "c", "\"_c")
vim.keymap.set("n", "C", "\"_C")
vim.keymap.set("v", "c", "\"_c")
vim.keymap.set("v", "C", "\"_C")
vim.keymap.set("n", "x", "\"_x")
vim.keymap.set("x", "p", function() return 'pgv"' .. vim.v.register .. "y" end, { remap = false, expr = true })
vim.keymap.set("t", "<Esc>", "<C-\\><C-n>")
vim.keymap.set("n", "<leader>tt", vim.cmd.term)
vim.keymap.set("n", "<leader>te", ":split<Cr><C-w><C-w>:term<Cr>:resize 10<Cr>i")
vim.keymap.set("n", "[d", function() return vim.diagnostic.jump({ count = -1, float = true }) end)
vim.keymap.set("n", "]d", function() return vim.diagnostic.jump({ count = 1, float = true }) end)
vim.keymap.set("n", "<leader>e", vim.diagnostic.open_float)
vim.keymap.set('n', '<leader>q', vim.diagnostic.setloclist, { desc = 'Open diagnostic [Q]uickfix list' })
vim.keymap.set('n', '<Esc>', '<cmd>nohlsearch<CR>')
vim.keymap.set('n', '<C-h>', '<C-w><C-h>', { desc = 'Move focus to the left window' })
vim.keymap.set('n', '<C-l>', '<C-w><C-l>', { desc = 'Move focus to the right window' })
vim.keymap.set('n', '<C-j>', '<C-w><C-j>', { desc = 'Move focus to the lower window' })
vim.keymap.set('n', '<C-k>', '<C-w><C-k>', { desc = 'Move focus to the upper window' })
